[profile.default]
src = "test"
out = "out"
libs = ["../lib"]
test = "test"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 1000

[profile.maximum]
fuzz = { runs = 10000000 }
invariant = { runs = 1000000, depth = 20 }
ffi = false
verbosity = 4

remappings = [
    "forge-std/=../lib/forge-std/src/",
    "openzeppelin/=../lib/openzeppelin-contracts/contracts/"
]
